# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: redarnet <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/01/07 11:44:19 by redarnet          #+#    #+#              #
#    Updated: 2020/01/07 11:47:11 by redarnet         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = cub3d.a

 gcc -L minilibx -lmlx -framework OpenGL -framework AppKit *c libft/*c get_next_line/*c
all : $(NAME)

